"""
report_generator.py
===================
Generates the final shortlist report in JSON and HTML formats.

The internship brief requires output as PDF/HTML/JSON with rubric breakdown.
We generate HTML (downloadable) and JSON (structured) from the same data.

Interview talking point:
  "I used Jinja2 templating for the HTML report so the report
   structure is cleanly separated from the Python logic.
   The JSON output is also generated — this makes the data
   machine-readable for any downstream system."
"""

import json
import datetime


# ─── HTML Report Template ─────────────────────────────────────────────────────
HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Candidate Shortlist Report</title>
<style>
  * {{ box-sizing: border-box; margin: 0; padding: 0; }}
  body {{ font-family: 'Segoe UI', Arial, sans-serif; background: #f5f7fa; color: #333; padding: 32px; }}
  .header {{ background: linear-gradient(135deg, #1a73e8, #0d47a1); color: white; padding: 32px; border-radius: 12px; margin-bottom: 32px; }}
  .header h1 {{ font-size: 28px; margin-bottom: 8px; }}
  .header p {{ opacity: 0.85; font-size: 14px; }}
  .meta-grid {{ display: grid; grid-template-columns: repeat(3, 1fr); gap: 16px; margin-bottom: 32px; }}
  .meta-card {{ background: white; padding: 20px; border-radius: 10px; box-shadow: 0 2px 8px rgba(0,0,0,0.08); text-align: center; }}
  .meta-card .number {{ font-size: 36px; font-weight: 700; color: #1a73e8; }}
  .meta-card .label {{ font-size: 13px; color: #666; margin-top: 4px; }}
  .section-title {{ font-size: 20px; font-weight: 600; margin-bottom: 16px; color: #1a1a2e; border-left: 4px solid #1a73e8; padding-left: 12px; }}
  .candidate-card {{ background: white; border-radius: 12px; box-shadow: 0 2px 12px rgba(0,0,0,0.08); margin-bottom: 24px; overflow: hidden; }}
  .card-header {{ padding: 20px 24px; display: flex; align-items: center; justify-content: space-between; border-bottom: 1px solid #f0f0f0; }}
  .rank-badge {{ background: #1a73e8; color: white; width: 36px; height: 36px; border-radius: 50%; display: flex; align-items: center; justify-content: center; font-weight: 700; font-size: 14px; flex-shrink: 0; }}
  .candidate-name {{ font-size: 18px; font-weight: 600; margin-left: 12px; }}
  .total-score {{ font-size: 28px; font-weight: 700; }}
  .hire-badge {{ padding: 6px 16px; border-radius: 20px; font-size: 13px; font-weight: 600; }}
  .hire {{ background: #e8f5e9; color: #2e7d32; }}
  .nohire {{ background: #fce4ec; color: #c62828; }}
  .card-body {{ padding: 24px; }}
  .scores-grid {{ display: grid; grid-template-columns: repeat(5, 1fr); gap: 12px; margin-bottom: 20px; }}
  .score-item {{ text-align: center; }}
  .score-bar-wrap {{ height: 6px; background: #e0e0e0; border-radius: 3px; margin: 6px 0; }}
  .score-bar {{ height: 6px; border-radius: 3px; background: #1a73e8; }}
  .score-num {{ font-size: 20px; font-weight: 700; color: #1a73e8; }}
  .score-dim {{ font-size: 11px; color: #888; margin-top: 4px; }}
  .justification-table {{ width: 100%; border-collapse: collapse; font-size: 13px; }}
  .justification-table th {{ background: #f5f7fa; padding: 10px 14px; text-align: left; font-weight: 600; color: #555; }}
  .justification-table td {{ padding: 10px 14px; border-bottom: 1px solid #f0f0f0; vertical-align: top; }}
  .tag-row {{ display: flex; flex-wrap: wrap; gap: 8px; margin-top: 12px; }}
  .tag {{ padding: 4px 12px; border-radius: 20px; font-size: 12px; }}
  .strength {{ background: #e8f5e9; color: #2e7d32; }}
  .gap {{ background: #fce4ec; color: #c62828; }}
  .override-note {{ background: #fff8e1; border: 1px solid #ffd54f; border-radius: 8px; padding: 12px 16px; margin-top: 12px; font-size: 13px; color: #795548; }}
  .summary {{ background: #f0f4ff; border-radius: 8px; padding: 14px; margin-top: 12px; font-size: 14px; line-height: 1.6; color: #444; }}
  .footer {{ text-align: center; font-size: 12px; color: #aaa; margin-top: 40px; }}
</style>
</head>
<body>
<div class="header">
  <h1>🤖 AI Candidate Shortlist Report</h1>
  <p>Role: {job_title} &nbsp;|&nbsp; Generated: {generated_at} &nbsp;|&nbsp; Powered by Gemini 1.5 Flash + LangChain</p>
</div>

<div class="meta-grid">
  <div class="meta-card"><div class="number">{total_candidates}</div><div class="label">Total Candidates</div></div>
  <div class="meta-card"><div class="number" style="color:#2e7d32">{shortlisted}</div><div class="label">Shortlisted (Hire)</div></div>
  <div class="meta-card"><div class="number" style="color:#c62828">{rejected}</div><div class="label">Not Shortlisted</div></div>
</div>

<div class="section-title">Ranked Candidates</div>

{candidate_cards}

<div class="footer">
  Generated by AI Resume Shortlisting Agent · Student Internship Project · Scores are AI-generated — human review recommended before final decisions.
</div>
</body>
</html>"""


CANDIDATE_CARD_TEMPLATE = """
<div class="candidate-card">
  <div class="card-header">
    <div style="display:flex;align-items:center">
      <div class="rank-badge">#{rank}</div>
      <div class="candidate-name">{candidate_name}</div>
    </div>
    <div style="display:flex;align-items:center;gap:16px">
      <div class="total-score" style="color:{score_color}">{weighted_total}/100</div>
      <span class="hire-badge {hire_class}">{recommendation}</span>
    </div>
  </div>
  <div class="card-body">
    <div class="scores-grid">
      {score_bars}
    </div>

    <table class="justification-table">
      <tr><th>Dimension</th><th>Score</th><th>Justification</th></tr>
      {justification_rows}
    </table>

    <div class="summary">{overall_summary}</div>

    <div class="tag-row">
      {strength_tags}
      {gap_tags}
    </div>

    {override_note}
  </div>
</div>"""


DIMENSION_LABELS = {
    "skills_match": "Skills Match (30%)",
    "experience_relevance": "Experience (25%)",
    "education_certifications": "Education (15%)",
    "projects_portfolio": "Projects (20%)",
    "communication_quality": "Communication (10%)",
}


def _score_color(total: float) -> str:
    if total >= 70:
        return "#2e7d32"
    elif total >= 50:
        return "#e65100"
    else:
        return "#c62828"


def generate_candidate_card_html(candidate: dict, rank: int) -> str:
    scores = candidate.get("scores", {})
    justifications = candidate.get("justifications", {})

    # Score bars
    score_bars = ""
    for dim, label in DIMENSION_LABELS.items():
        score = scores.get(dim, 0)
        pct = score * 10
        short_label = label.split(" (")[0]
        score_bars += f"""
        <div class="score-item">
          <div class="score-num">{score}</div>
          <div class="score-bar-wrap"><div class="score-bar" style="width:{pct}%"></div></div>
          <div class="score-dim">{short_label}</div>
        </div>"""

    # Justification rows
    just_rows = ""
    for dim, label in DIMENSION_LABELS.items():
        score = scores.get(dim, 0)
        just = justifications.get(dim, "N/A")
        just_rows += f"<tr><td>{label}</td><td><b>{score}/10</b></td><td>{just}</td></tr>"

    # Strength / gap tags
    strengths = "".join(
        f'<span class="tag strength">✓ {s}</span>'
        for s in candidate.get("key_strengths", [])
    )
    gaps = "".join(
        f'<span class="tag gap">✗ {g}</span>'
        for g in candidate.get("key_gaps", [])
    )

    # Override note
    override_note = ""
    if candidate.get("manually_overridden"):
        log = candidate["override_log"][-1]
        override_note = f"""
        <div class="override-note">
          ⚠️ <b>Human override applied</b> on {log['timestamp'][:10]}<br>
          Reason: {log['reason']}
        </div>"""

    total = candidate.get("weighted_total", 0)
    rec = candidate.get("recommendation", "NO HIRE")

    return CANDIDATE_CARD_TEMPLATE.format(
        rank=rank,
        candidate_name=candidate.get("candidate_name", "Unknown"),
        weighted_total=total,
        score_color=_score_color(total),
        hire_class="hire" if rec == "HIRE" else "nohire",
        recommendation="✅ HIRE" if rec == "HIRE" else "❌ NO HIRE",
        score_bars=score_bars,
        justification_rows=just_rows,
        overall_summary=candidate.get("overall_summary", "No summary available."),
        strength_tags=strengths,
        gap_tags=gaps,
        override_note=override_note,
    )


def generate_html_report(ranked_candidates: list, parsed_jd: dict) -> str:
    """
    Generates a complete HTML report string.

    Args:
        ranked_candidates : Sorted list from ranker.rank_candidates()
        parsed_jd         : Parsed JD dict

    Returns:
        HTML string ready to be downloaded or displayed.
    """
    valid = [c for c in ranked_candidates if "weighted_total" in c]
    hire_count = sum(1 for c in valid if c.get("recommendation") == "HIRE")

    cards_html = ""
    for i, candidate in enumerate(valid, start=1):
        cards_html += generate_candidate_card_html(candidate, i)

    return HTML_TEMPLATE.format(
        job_title=parsed_jd.get("job_title", "Unknown Role"),
        generated_at=datetime.datetime.now().strftime("%d %b %Y, %I:%M %p"),
        total_candidates=len(valid),
        shortlisted=hire_count,
        rejected=len(valid) - hire_count,
        candidate_cards=cards_html,
    )


def generate_json_report(ranked_candidates: list, parsed_jd: dict) -> str:
    """
    Generates a clean JSON report string.

    Returns:
        Pretty-printed JSON string.
    """
    report = {
        "report_metadata": {
            "generated_at": datetime.datetime.now().isoformat(),
            "job_title": parsed_jd.get("job_title", "Unknown"),
            "total_candidates": len(ranked_candidates),
            "shortlisted": sum(
                1 for c in ranked_candidates if c.get("recommendation") == "HIRE"
            ),
        },
        "rubric_weights": {
            "skills_match": "30%",
            "experience_relevance": "25%",
            "education_certifications": "15%",
            "projects_portfolio": "20%",
            "communication_quality": "10%",
        },
        "candidates": [
            {
                "rank": c.get("rank"),
                "candidate_name": c.get("candidate_name", "Unknown"),
                "filename": c.get("filename", ""),
                "weighted_total": c.get("weighted_total"),
                "recommendation": c.get("recommendation"),
                "scores": c.get("scores", {}),
                "justifications": c.get("justifications", {}),
                "key_strengths": c.get("key_strengths", []),
                "key_gaps": c.get("key_gaps", []),
                "overall_summary": c.get("overall_summary", ""),
                "manually_overridden": c.get("manually_overridden", False),
            }
            for c in ranked_candidates
            if "weighted_total" in c
        ],
    }
    return json.dumps(report, indent=2)
